import { Router } from 'express';
import auth from './auth.js';
import restaurants from './restaurants.js';
import menu from './menu.js';
import offers from './offers.js';
import ads from './ads.js';
import customers from './customers.js';
import captains from './captains.js';
import orders from './orders.js';
import payments from './payments.js';
import stats from './stats.js';
import whatsapp from './whatsapp.js';
import branches from './branches.js';
import reports from './reports.js';
import dbadmin from './dbadmin.js';
import settings from './settings.js';
import businessTypes from './businessTypes.js';
import registrations from './registrations.js';
import reportRecipients from './reportRecipients.js';
import adRequests from './adRequests.js';
import users from './users.js';

const router = Router();
router.use('/auth', auth);
router.use('/restaurants', restaurants);
router.use('/menu', menu);
router.use('/offers', offers);
router.use('/ads', ads);
router.use('/customers', customers);
router.use('/captains', captains);
router.use('/orders', orders);
router.use('/payments', payments);
router.use('/stats', stats);
router.use('/whatsapp', whatsapp);
router.use('/branches', branches);
router.use('/reports', reports);
router.use('/dbadmin', dbadmin);
router.use('/settings', settings);
router.use('/business-types', businessTypes);
router.use('/registrations', registrations);
router.use('/report-recipients', reportRecipients);
router.use('/ad-requests', adRequests);
router.use('/users', users);
export default router;
